# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

owners = Owner.create([{username: "Royce2222", password_digest: BCrypt::Password.create("12345"), email: "royce2222@gmail.com" , dog_name: "Peanut", profile_pic: "xyz"}, {username: "Hammy007", password_digest: BCrypt::Password.create("12345"), email: "morley.hamilton@gmail.com", dog_name: "Bowie", profile_pic: "zad"}, {username: "Sabrina101", password_digest: BCrypt::Password.create("12345"), email: "skortlan@tulane.edu", dog_name: "Tilda", profile_pic: "dgd"}, {username: "Nonni", password_digest: BCrypt::Password.create("12345"), email: "veronica_martinez@gmail.com", dog_name: "MONEY", profile_pic: "qwe"}, {username: "Pizza220", password_digest: BCrypt::Password.create("12345"), email: "p_izza220@nyu.edu", dog_name: "Watson", profile_pic: "453"}, {username: "BigBadBrad", password_digest: BCrypt::Password.create("12345"), email: "bg@daypitney.com", dog_name: "Samantha", profile_pic: "gf"}, {username: "Rachel", password_digest: BCrypt::Password.create("12345"), email: "Rachel@gmail.com" , dog_name: "Gidget", profile_pic: "xyz"}, {username: "Kit", password_digest: BCrypt::Password.create("12345"), email: "kat@gmail.com" , dog_name: "Willard", profile_pic: "xyz"}, {username: "Will", password_digest: BCrypt::Password.create("12345"), email: "will@gmail.com" , dog_name: "Princessa", profile_pic: "xyz"}, {username: "Christina", password_digest: BCrypt::Password.create("12345"), email: "Betty@gmail.com" , dog_name: "Cosmo", profile_pic: "xyz"}, {username: "Rich and Eliza", password_digest: BCrypt::Password.create("12345"), email: "RE@gmail.com" , dog_name: "Hazel", profile_pic: "xyz"}])
